// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC07y9FECI5eW35voAnfbXAs-G_fJLkECg',
    appId: '1:275192622556:web:d1ab349f3b5979bd98b319',
    messagingSenderId: '275192622556',
    projectId: 'camerin-f31b1',
    authDomain: 'camerin-f31b1.firebaseapp.com',
    storageBucket: 'camerin-f31b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByAX9St8LVtZdsbOvQByMfZkKGsY5SbbA',
    appId: '1:275192622556:android:3d51c90b846e468e98b319',
    messagingSenderId: '275192622556',
    projectId: 'camerin-f31b1',
    storageBucket: 'camerin-f31b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTdKJEUpPrT33KMQYg7-yOP5T6W5eULMA',
    appId: '1:275192622556:ios:6db786f7546db96898b319',
    messagingSenderId: '275192622556',
    projectId: 'camerin-f31b1',
    storageBucket: 'camerin-f31b1.appspot.com',
    iosBundleId: 'com.example.camerin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTdKJEUpPrT33KMQYg7-yOP5T6W5eULMA',
    appId: '1:275192622556:ios:7771421b999c05f898b319',
    messagingSenderId: '275192622556',
    projectId: 'camerin-f31b1',
    storageBucket: 'camerin-f31b1.appspot.com',
    iosBundleId: 'com.example.camerin.RunnerTests',
  );
}
